# Generated by Django 6.0 on 2025-12-24 19:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(max_length=20)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('position', models.CharField(choices=[('dev', 'Software Developer'), ('designer', 'UI/UX Designer'), ('devops', 'DevOps Engineer'), ('data', 'Data Scientist'), ('security', 'Security Analyst'), ('pm', 'Project Manager'), ('marketing', 'Marketing Specialist'), ('sales', 'Sales Executive'), ('intern', 'Intern'), ('other', 'Other')], max_length=50)),
                ('cover_letter', models.TextField()),
                ('resume', models.FileField(upload_to='resumes/')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Career Application',
                'verbose_name_plural': 'Career Applications',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_returning', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.TextField()),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_spam', models.BooleanField(default=False)),
                ('verification_token', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-date_sent'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_url', models.URLField()),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('referrer', models.URLField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Page View',
                'verbose_name_plural': 'Page Views',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(max_length=20)),
                ('service', models.CharField(choices=[('web', 'Web Development'), ('mobile', 'Mobile App Development'), ('ai', 'AI/ML Solutions'), ('cloud', 'Cloud Services'), ('cyber', 'Cybersecurity'), ('consulting', 'IT Consulting'), ('marketing', 'Digital Marketing'), ('data', 'Data Analytics'), ('custom', 'Custom Solution')], max_length=50)),
                ('budget', models.CharField(choices=[('1k-5k', '$1,000 - $5,000'), ('5k-10k', '$5,000 - $10,000'), ('10k-25k', '$10,000 - $25,000'), ('25k-50k', '$25,000 - $50,000'), ('50k+', '$50,000+'), ('custom', 'Custom Budget')], max_length=20)),
                ('requirements', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Proposal Request',
                'verbose_name_plural': 'Proposal Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('login_attempt', 'Login Attempt'), ('failed_login', 'Failed Login'), ('suspicious', 'Suspicious Activity'), ('spam', 'Spam Detection'), ('bruteforce', 'Brute Force Attempt'), ('sql_injection', 'SQL Injection Attempt'), ('xss', 'XSS Attempt'), ('bot', 'Bot Detection'), ('other', 'Other')], max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Security Log',
                'verbose_name_plural': 'Security Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceInquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(max_length=20)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('service', models.CharField(choices=[('web', 'Web Development'), ('mobile', 'Mobile App Development'), ('ai', 'AI/ML Solutions'), ('cloud', 'Cloud Services'), ('cyber', 'Cybersecurity'), ('consulting', 'IT Consulting'), ('marketing', 'Digital Marketing'), ('data', 'Data Analytics'), ('other', 'Other')], max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Service Inquiry',
                'verbose_name_plural': 'Service Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('verification_token', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('is_user', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='main.chatbotsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
